version: '3'

networks:
  mynetwork:
    driver: bridge

# volumes:
#   wordpress-data:
#     name: wordpress-data
#     driver: local
#     driver_opts:
#             device: /home/$USER/data/wordpress
#             o: bind
#             type: none
#   database:
#     name: database
#     driver: local
#     driver_opts:
#       device: /home/$USER/data/mariadb
#       o: bind
#       type: none

services:
  # mariadb:
  #   build:
  #     context: mariadb/
  #   image: mariadb
  #   container_name: mariadb
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - database:/var/lib/mysql
  #   expose:
  #     - 3306
  #   env_file:
  #     - .env
  #   restart:
  #     always
  
  # wordpress:
  #   build: 
  #     context: wordpress/
  #   container_name: wordpress
  #   image: wordpress
  #   networks:
  #     - mynetwork
  #   expose:
  #     - 9000
  #   volumes:
  #     - wordpress-data:/var/www/html
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mariadb
  #   restart:
  #     always
    
  nginx:
    build: 
      context: mynginx/
    container_name: nginx
    image: nginx
    networks:
      - mynetwork
    ports:
      - 443:443
    # volumes:
    #   - wordpress-data:/var/www/html
    env_file:
      - .env
    # depends_on:
    #   - wordpress
    restart:
      always
